// primsa seed

import { PrismaClient } from '@prisma/client';
import { CategoryModel } from 'src/model/modelsType';
import nutritional_data from './nutritionalData.json';

export interface NutritionalData {
  id: string;
  foodId: string;
  categoryId: string;
  preparationId: string;
  energy?: number;
  protein?: number;
  total_fat?: number;
  carbohydrate?: number;
  total_dietary_fiber?: number;
  cholesterol?: number;
  saturated_fatty_acids?: number;
  monounsaturated_fatty_acids?: number;
  polyunsaturated_fatty_acids?: number;
  linoleic_acid?: number;
  linolenic_acid?: number;
  trans_fatty_acids?: number;
  sugar?: number;
  added_sugar?: number;
  calcium?: number;
  magnesium?: number;
  manganese?: number;
  phosphorus?: number;
  iron?: number;
  sodium?: number;
  added_sodium?: number;
  potassium?: number;
  copper?: number;
  zinc?: number;
  selenium?: number;
}

const nutritionalData: NutritionalData[] = nutritional_data;

const prisma = new PrismaClient();

const category: CategoryModel[] = [
  { id: '100', name: 'Cereais e leguminosas' },
  { id: '101', name: 'Hortaliças tuberosas' },
  { id: '102', name: 'Farinhas, féculas e massas' },
  { id: '103', name: 'Cocos, castanhas e nozes ' },
  { id: '104', name: 'Hortaliças folhosas, frutosas e outras ' },
  { id: '105', name: 'Frutas' },
  { id: '106', name: 'Açúcares e produtos de confeitaria  ' },
  { id: '107', name: 'Sais e condimentos ' },
  { id: '108', name: 'Carnes e vísceras' },
  { id: '109', name: 'Pescados e frutos do mar ' },
  { id: '110', name: 'Enlatados e conservas ' },
  { id: '111', name: 'Aves e ovos   ' },
  { id: '112', name: 'Laticínios ' },
  { id: '113', name: 'Panificados ' },
  { id: '114', name: 'Carnes industrializadas ' },
  { id: '115', name: 'Bebidas não alcoólicas e infusões ' },
  { id: '116', name: 'Bebidas alcoólicas ' },
  { id: '117', name: 'Óleos e gorduras ' },
  { id: '118', name: 'Miscelâneas ' },
];

const food = [
  { id: '1', name: 'Arroz integral.', categoryId: '100' },
  { id: '10', name: 'Canjiquinha de milho em grão', categoryId: '100' },
  { id: '100', name: 'Inhame caraquento (cará)', categoryId: '101' },
  { id: '1007', name: 'Chuleta', categoryId: '108' },
  { id: '101', name: 'Batata (não especificada)', categoryId: '101' },
  { id: '1011', name: 'Filé não especificado', categoryId: '108' },
  { id: '1022', name: 'Miúdo de bode', categoryId: '108' },
  { id: '1023', name: 'Pé suíno fresco', categoryId: '108' },
  { id: '1026', name: 'Carne bovina', categoryId: '108' },
  { id: '1028', name: 'Carne bovina', categoryId: '108' },
  { id: '1041', name: 'Lombo não especificado', categoryId: '108' },
  { id: '1046', name: 'Músculo não especificado', categoryId: '108' },
  { id: '1048', name: 'Ossada não especificada', categoryId: '108' },
  { id: '1052', name: 'Carne de segunda', categoryId: '108' },
  { id: '1062', name: 'Contrafilé orgânico', categoryId: '108' },
  { id: '1063', name: 'Bisteca orgânica', categoryId: '108' },
  {
    id: '1065',
    name: 'Cabeça de lombo (carne bovina) orgânica',
    categoryId: '108',
  },
  { id: '1068', name: 'Tatu (lagarto redondo) orgânico', categoryId: '108' },
  {
    id: '1069',
    name: 'Peixe de mar (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  {
    id: '1078',
    name: 'Peixe de mar salgado (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  { id: '1085', name: 'Camarão', categoryId: '109' },
  { id: '1086', name: 'Camarão', categoryId: '109' },
  { id: '1097', name: 'Siri', categoryId: '109' },
  { id: '1100', name: 'Bau (siri)', categoryId: '109' },
  { id: '1101', name: 'Goiá', categoryId: '109' },
  { id: '1102', name: 'Caranguejo', categoryId: '109' },
  { id: '1105', name: 'Guaiamu', categoryId: '109' },
  { id: '1106', name: 'Marisco', categoryId: '109' },
  { id: '1110', name: 'Ostra', categoryId: '109' },
  { id: '1111', name: 'Lula', categoryId: '109' },
  { id: '1112', name: 'Sururu', categoryId: '109' },
  { id: '1114', name: 'Bacalhau', categoryId: '109' },
  { id: '1122', name: 'Ovas de peixe (qualquer espécie)', categoryId: '109' },
  {
    id: '1124',
    name: 'Peixe de água doce (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  { id: '113', name: 'Mandioquinha', categoryId: '101' },
  {
    id: '1135',
    name: 'Peixe de água doce salgado (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  { id: '1142', name: 'Tracajá', categoryId: '109' },
  {
    id: '1143',
    name: 'Peixe não especificado (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  {
    id: '1153',
    name: 'Peixe não especificado salgado (inteiro, em posta, em filé, etc.)',
    categoryId: '109',
  },
  { id: '1158', name: 'Azeitona', categoryId: '110' },
  { id: '1159', name: 'Ervilha em conserva', categoryId: '110' },
  { id: '1160', name: 'Petit-pois', categoryId: '110' },
  { id: '1161', name: 'Milho verde em conserva', categoryId: '110' },
  { id: '1162', name: 'Palmito em conserva', categoryId: '110' },
  { id: '1163', name: 'Cogumelo em conserva', categoryId: '110' },
  { id: '1164', name: 'Champignon em conserva', categoryId: '110' },
  { id: '1165', name: 'Aspargo em conserva', categoryId: '110' },
  { id: '1166', name: 'Repolho em conserva', categoryId: '110' },
  { id: '1167', name: 'Chucrute', categoryId: '110' },
  {
    id: '1168',
    name: 'Legume não especificado em conserva',
    categoryId: '110',
  },
  { id: '1169', name: 'Creme de cebola (sopa desidratada)', categoryId: '110' },
  { id: '117', name: 'Rabanete', categoryId: '101' },
  {
    id: '1170',
    name: 'Creme de legumes (sopa desidratada)',
    categoryId: '110',
  },
  { id: '1171', name: 'Yakissoba', categoryId: '110' },
  {
    id: '1172',
    name: 'Milho verde com ervilha em conserva',
    categoryId: '110',
  },
  { id: '1176', name: 'Feijoada', categoryId: '110' },
  {
    id: '1177',
    name: 'Feijão branco com dobradinha em conserva',
    categoryId: '110',
  },
  { id: '1178', name: 'Cozido', categoryId: '110' },
  { id: '1179', name: 'Pasta de carne em conserva', categoryId: '110' },
  { id: '1180', name: 'Pasta de presunto em conserva', categoryId: '110' },
  { id: '1181', name: 'Pasta de galinha em conserva', categoryId: '110' },
  { id: '1182', name: 'Carne bovina em conserva', categoryId: '110' },
  { id: '1183', name: 'Almôndega', categoryId: '110' },
  { id: '1184', name: 'Kitute bovino', categoryId: '110' },
  { id: '1185', name: 'Almôndega ao molho em conserva', categoryId: '110' },
  { id: '1186', name: 'Kitute suíno', categoryId: '110' },
  { id: '1187', name: 'Presuntada', categoryId: '110' },
  { id: '1188', name: 'Fiambre', categoryId: '110' },
  { id: '1192', name: 'Salsicha em conserva', categoryId: '110' },
  { id: '1193', name: 'Sardinha em conserva', categoryId: '110' },
  { id: '1194', name: 'Atum em conserva', categoryId: '110' },
  { id: '1195', name: 'Pepino em conserva', categoryId: '110' },
  { id: '1196', name: 'Pasta de peixe em conserva', categoryId: '110' },
  { id: '1197', name: 'Picles', categoryId: '110' },
  { id: '1198', name: 'Nabo em conserva', categoryId: '110' },
  { id: '1199', name: 'Strogonoff', categoryId: '110' },
  { id: '120', name: 'Beterraba', categoryId: '101' },
  { id: '1200', name: 'Salmão em conserva', categoryId: '110' },
  {
    id: '1201',
    name: 'Creme de cebola (sopa desidratada) light',
    categoryId: '110',
  },
  {
    id: '1202',
    name: 'Creme de legumes (sopa desidratada) light',
    categoryId: '110',
  },
  {
    id: '1203',
    name: 'Yakissoba (sopa de legumes desidratada) light',
    categoryId: '110',
  },
  { id: '1204', name: 'Atum em conserva light', categoryId: '110' },
  { id: '1205', name: 'Frango inteiro', categoryId: '111' },
  {
    id: '1214',
    name: 'Parte de galinha ou frango não especificada',
    categoryId: '111',
  },
  { id: '1224', name: 'Frango em pedaços', categoryId: '111' },
  { id: '1238', name: 'Galinha em pedaços', categoryId: '111' },
  { id: '1247', name: 'Carne de galinha', categoryId: '111' },
  { id: '1259', name: 'Peito de galinha ou frango', categoryId: '111' },
  { id: '126', name: 'Cenoura', categoryId: '101' },
  { id: '1271', name: 'Filé de frango', categoryId: '111' },
  { id: '1283', name: 'Carcaça de galinha ou frango', categoryId: '111' },
  { id: '1288', name: 'Asa de galinha ou frango', categoryId: '111' },
  { id: '1297', name: 'Drumete de galinha ou frango', categoryId: '111' },
  { id: '1303', name: 'Pescoço de galinha ou frango', categoryId: '111' },
  { id: '1308', name: 'Pé de galinha ou frango', categoryId: '111' },
  { id: '1315', name: 'Miúdo de galinha ou frango', categoryId: '111' },
  { id: '1320', name: 'Moela de galinha ou frango', categoryId: '111' },
  { id: '1328', name: 'Coração de frango', categoryId: '111' },
  { id: '1333', name: 'Fígado de galinha ou frango', categoryId: '111' },
  { id: '1336', name: 'Canja', categoryId: '111' },
  { id: '1337', name: 'Peru em pedaço não especificado', categoryId: '111' },
  { id: '1341', name: 'Peito de peru', categoryId: '111' },
  { id: '1348', name: 'Asa de peru', categoryId: '111' },
  { id: '1350', name: 'Chester', categoryId: '111' },
  { id: '1353', name: 'Tender', categoryId: '111' },
  { id: '1354', name: 'Nambu', categoryId: '111' },
  { id: '1355', name: 'Nuggets de frango', categoryId: '111' },
  { id: '1360', name: 'Steak de frango', categoryId: '111' },
  { id: '1366', name: 'Codorna', categoryId: '111' },
  { id: '1367', name: 'Pé e asa de galinha ou frango', categoryId: '111' },
  { id: '137', name: 'Nabo', categoryId: '101' },
  { id: '1370', name: 'Ovo de galinha', categoryId: '111' },
  { id: '1382', name: 'Ovo de codorna', categoryId: '111' },
  {
    id: '1387',
    name: "Galinha-d'angola abatida, congelada ou viva",
    categoryId: '111',
  },
  { id: '1389', name: 'Capote', categoryId: '111' },
  { id: '139', name: 'Açafrão', categoryId: '101' },
  { id: '1392', name: 'Mutum', categoryId: '111' },
  { id: '1393', name: 'Pato em pedaços', categoryId: '111' },
  { id: '1395', name: 'Peito de pato', categoryId: '111' },
  { id: '1396', name: 'Carne de pato', categoryId: '111' },
  { id: '1399', name: 'Peito de peru light', categoryId: '111' },
  { id: '140', name: 'Batata-inglesa orgânica', categoryId: '101' },
  { id: '1402', name: 'Frango inteiro orgânico', categoryId: '111' },
  { id: '1404', name: 'Filé de frango orgânico', categoryId: '111' },
  { id: '1408', name: 'Leite de vaca integral', categoryId: '112' },
  { id: '1409', name: 'Leite de vaca fresco', categoryId: '112' },
  { id: '141', name: 'Creme de arroz', categoryId: '102' },
  { id: '1410', name: 'Leite de cabra', categoryId: '112' },
  { id: '1411', name: 'Leite em pó integral', categoryId: '112' },
  { id: '1412', name: 'Leite em pó desnatado', categoryId: '112' },
  { id: '1413', name: 'Leite em pó', categoryId: '112' },
  { id: '1414', name: 'Leite condensado', categoryId: '112' },
  { id: '1415', name: 'Leite beijinho', categoryId: '112' },
  { id: '1416', name: 'Creme de leite', categoryId: '112' },
  { id: '1417', name: 'Chantilly', categoryId: '112' },
  { id: '1418', name: 'Iogurte de qualquer sabor', categoryId: '112' },
  { id: '1419', name: 'Iogurte desnatado', categoryId: '112' },
  { id: '142', name: 'Arrozina', categoryId: '102' },
  { id: '1420', name: 'Iogurte natural', categoryId: '112' },
  { id: '1421', name: 'Yakult de qualquer sabor', categoryId: '112' },
  { id: '1422', name: 'Bebida láctea', categoryId: '112' },
  { id: '1423', name: 'Leite fermentado', categoryId: '112' },
  { id: '1424', name: 'Coalhada', categoryId: '112' },
  { id: '1425', name: 'Manteiga com ou sem sal', categoryId: '112' },
  { id: '1426', name: 'Manteiga de garrafa', categoryId: '112' },
  { id: '1427', name: 'Margarina com ou sem sal', categoryId: '112' },
  { id: '1428', name: 'Queijo prato', categoryId: '112' },
  { id: '1429', name: 'Queijo colonial', categoryId: '112' },
  { id: '143', name: 'Mucilon', categoryId: '102' },
  { id: '1430', name: 'Queijo de colônia', categoryId: '112' },
  { id: '1431', name: 'Queijo muçarela', categoryId: '112' },
  { id: '1432', name: 'Muçarela', categoryId: '112' },
  { id: '1433', name: 'Muçarela de búfala', categoryId: '112' },
  { id: '1434', name: 'Queijo de búfala', categoryId: '112' },
  { id: '1435', name: 'Queijo de reino', categoryId: '112' },
  { id: '1436', name: 'Queijo de minas', categoryId: '112' },
  { id: '1437', name: 'Queijo de manteiga', categoryId: '112' },
  { id: '1438', name: 'Quechimia', categoryId: '112' },
  { id: '1439', name: 'Queijo de coalho', categoryId: '112' },
  { id: '144', name: 'Mingau de arroz', categoryId: '102' },
  { id: '1440', name: 'Queijo canastra', categoryId: '112' },
  { id: '1441', name: 'Queijo ricota', categoryId: '112' },
  { id: '1442', name: 'Leite de soja com sabor', categoryId: '112' },
  { id: '1443', name: 'Ades original', categoryId: '112' },
  { id: '1444', name: 'Queijo ralado', categoryId: '112' },
  { id: '1445', name: 'Queijo provolone', categoryId: '112' },
  { id: '1446', name: 'Queijo polenguinho', categoryId: '112' },
  { id: '1447', name: 'Requeijão', categoryId: '112' },
  { id: '1448', name: 'Queijo cremoso', categoryId: '112' },
  { id: '1449', name: 'Queijo não especificado', categoryId: '112' },
  { id: '145', name: 'Croquinhos de arroz', categoryId: '102' },
  { id: '1450', name: 'Leite com sabor', categoryId: '112' },
  { id: '1451', name: 'Leite achocolatado', categoryId: '112' },
  { id: '1452', name: 'Leite aRomãtizado', categoryId: '112' },
  { id: '1453', name: 'Bebida achocolatada', categoryId: '112' },
  { id: '1454', name: 'Nata', categoryId: '112' },
  { id: '1455', name: 'Queijo gorgonzola', categoryId: '112' },
  { id: '1456', name: 'Tofu', categoryId: '112' },
  { id: '1457', name: 'Leite de soja em pó', categoryId: '112' },
  { id: '1458', name: 'Leite de vaca desnatado', categoryId: '112' },
  { id: '1459', name: 'Leite de vaca semidesnatado', categoryId: '112' },
  { id: '146', name: 'Farinha de aveia', categoryId: '102' },
  {
    id: '1460',
    name: 'Leite não especificado pasteurizado',
    categoryId: '112',
  },
  { id: '1461', name: 'Iogurte de qualquer sabor light', categoryId: '112' },
  { id: '1462', name: 'Iogurte de qualquer sabor diet', categoryId: '112' },
  { id: '1463', name: 'Margarina light', categoryId: '112' },
  { id: '1464', name: 'Leite de vaca integral orgânico', categoryId: '112' },
  { id: '1465', name: 'Leite de vaca fresco orgânico', categoryId: '112' },
  {
    id: '1466',
    name: 'Leite semidesnatado de vaca orgânico',
    categoryId: '112',
  },
  { id: '1467', name: 'Creme de leite orgânico', categoryId: '112' },
  { id: '1468', name: 'Iogurte de qualquer sabor orgânico', categoryId: '112' },
  {
    id: '1469',
    name: 'Iogurte de qualquer sabor desnatado orgânico',
    categoryId: '112',
  },
  { id: '147', name: 'Aveia em flocos', categoryId: '102' },
  {
    id: '1470',
    name: 'Iogurte natural de qualquer sabor orgânico',
    categoryId: '112',
  },
  { id: '1471', name: 'Muçarela light', categoryId: '112' },
  { id: '1472', name: 'Queijo muçarela light', categoryId: '112' },
  { id: '1473', name: 'Leite de soja com sabor light', categoryId: '112' },
  { id: '1474', name: 'Ades light', categoryId: '112' },
  { id: '1475', name: 'Creme de leite light', categoryId: '112' },
  { id: '1476', name: 'Queijo prato light', categoryId: '112' },
  { id: '1477', name: 'Queijo de minas light', categoryId: '112' },
  { id: '1478', name: 'Queijo de coalho light', categoryId: '112' },
  { id: '1479', name: 'Queijo ricota light', categoryId: '112' },
  { id: '148', name: 'Fubá de milho', categoryId: '102' },
  { id: '1480', name: 'Queijo ralado light', categoryId: '112' },
  { id: '1481', name: 'Queijo polenguinho light', categoryId: '112' },
  { id: '1482', name: 'Requeijão light', categoryId: '112' },
  { id: '1483', name: 'Queijo não especificado light', categoryId: '112' },
  { id: '1484', name: 'Leite achocolatado light', categoryId: '112' },
  { id: '1485', name: 'Bebida achocolatada light', categoryId: '112' },
  { id: '1486', name: 'Leite com sabor diet', categoryId: '112' },
  { id: '1487', name: 'Leite achocolatado diet', categoryId: '112' },
  { id: '1488', name: 'Bebida achocolatada diet', categoryId: '112' },
  { id: '1489', name: 'Leite de soja em pó light', categoryId: '112' },
  { id: '149', name: 'Farinha de milho', categoryId: '102' },
  { id: '1490', name: 'Leite em pó com sabor', categoryId: '112' },
  { id: '1491', name: 'Manteiga com ou sem sal light', categoryId: '112' },
  { id: '1492', name: 'Queijo de minas frescal orgânico', categoryId: '112' },
  { id: '1493', name: 'Queijo de coalho frescal orgânico', categoryId: '112' },
  { id: '1494', name: 'Pão de hambúrguer', categoryId: '113' },
  { id: '1495', name: 'Pão de sal', categoryId: '113' },
  { id: '1496', name: 'Pão doce', categoryId: '113' },
  { id: '1497', name: 'Chineque', categoryId: '113' },
  { id: '1498', name: 'Chineque com farofa', categoryId: '113' },
  { id: '1499', name: 'Pão de mel', categoryId: '113' },
  { id: '150', name: 'Puba de milho', categoryId: '102' },
  { id: '1500', name: 'Panetone', categoryId: '113' },
  { id: '1501', name: 'Bisnaguinha', categoryId: '113' },
  { id: '1502', name: 'Croissant', categoryId: '113' },
  {
    id: '1503',
    name: 'Pão de forma industrializado de qualquer marca',
    categoryId: '113',
  },
  { id: '1504', name: 'Pão de queijo', categoryId: '113' },
  { id: '1505', name: 'Pão de milho', categoryId: '113' },
  { id: '1506', name: 'Pão integral', categoryId: '113' },
  { id: '1507', name: 'Pão não especificado', categoryId: '113' },
  { id: '1508', name: 'Torrada de qualquer pão', categoryId: '113' },
  { id: '1509', name: 'Rosca doce', categoryId: '113' },
  { id: '151', name: 'Puba de fubá', categoryId: '102' },
  { id: '1510', name: 'Rosquinha doce', categoryId: '113' },
  { id: '1511', name: 'Rosca salgada', categoryId: '113' },
  { id: '1512', name: 'Rosquinha salgada', categoryId: '113' },
  { id: '1513', name: 'Biscoito salgado', categoryId: '113' },
  { id: '1514', name: 'Presuntinho biscoito', categoryId: '113' },
  { id: '1515', name: 'Biscoito de polvilho', categoryId: '113' },
  { id: '1516', name: 'Bolacha salgada', categoryId: '113' },
  { id: '1517', name: 'Chips (salgadinhos)', categoryId: '113' },
  { id: '1518', name: 'Baconzitos', categoryId: '113' },
  { id: '1519', name: 'Biscoito salgado integral', categoryId: '113' },
  { id: '152', name: 'Milho moído', categoryId: '102' },
  { id: '1520', name: 'Biscoito doce', categoryId: '113' },
  { id: '1521', name: 'Cavaco chinês', categoryId: '113' },
  { id: '1522', name: 'Sequilho', categoryId: '113' },
  { id: '1523', name: 'Tareço', categoryId: '113' },
  { id: '1524', name: 'Solda', categoryId: '113' },
  { id: '1525', name: 'Brevidade', categoryId: '113' },
  { id: '1526', name: 'Bolacha doce', categoryId: '113' },
  { id: '1527', name: 'Maria maluca (bolacha doce)', categoryId: '113' },
  { id: '1528', name: 'Quebra-quebra', categoryId: '113' },
  { id: '1529', name: 'Rocambole', categoryId: '113' },
  { id: '153', name: 'Mingau de milho', categoryId: '102' },
  { id: '1530', name: 'Cuca de qualquer tipo', categoryId: '113' },
  { id: '1531', name: 'Bolo de milho', categoryId: '113' },
  { id: '1532', name: 'Amidomil (bolinho)', categoryId: '113' },
  { id: '1533', name: 'Angusor de milho', categoryId: '113' },
  { id: '1534', name: 'Grustoli (bolinho doce)', categoryId: '113' },
  { id: '1535', name: 'Bolo de aipim', categoryId: '113' },
  { id: '1536', name: 'Bolo de tapioca', categoryId: '113' },
  { id: '1537', name: 'Bolo de macaxeira', categoryId: '113' },
  { id: '1538', name: 'Bolo de goma', categoryId: '113' },
  { id: '1539', name: 'Bolo de batata-doce', categoryId: '113' },
  { id: '154', name: 'Amido de milho', categoryId: '102' },
  { id: '1540', name: 'Bolo de arroz', categoryId: '113' },
  { id: '1541', name: 'Bolo de cará', categoryId: '113' },
  { id: '1542', name: 'Tortas doces de qualquer sabor', categoryId: '113' },
  { id: '1543', name: 'Tortas salgadas de qualquer sabor', categoryId: '113' },
  { id: '1544', name: 'Sonho', categoryId: '113' },
  {
    id: '1545',
    name: 'Filhos (bolinho de farinha de trigo e ovos)',
    categoryId: '113',
  },
  { id: '1546', name: 'Bolo de chocolate', categoryId: '113' },
  { id: '1547', name: 'Brioche', categoryId: '113' },
  { id: '1548', name: 'Bolo de laranja', categoryId: '113' },
  { id: '1549', name: 'Bolo de coco', categoryId: '113' },
  { id: '155', name: 'Amido de arroz', categoryId: '102' },
  { id: '1550', name: 'Bolo de cenoura', categoryId: '113' },
  { id: '1551', name: 'Bolo de trigo', categoryId: '113' },
  { id: '1552', name: 'Broa', categoryId: '113' },
  { id: '1553', name: 'Biscoito recheado', categoryId: '113' },
  { id: '1554', name: 'Waffer (biscoito)', categoryId: '113' },
  { id: '1555', name: 'Alfajores (biscoito)', categoryId: '113' },
  { id: '1556', name: 'Bolacha recheada', categoryId: '113' },
  { id: '1557', name: 'Rosca recheada', categoryId: '113' },
  {
    id: '1558',
    name: 'Rosquinha recheada de qualquer sabor',
    categoryId: '113',
  },
  { id: '1559', name: 'Biscoito não especificado', categoryId: '113' },
  { id: '156', name: 'Cremogema', categoryId: '102' },
  { id: '1560', name: 'Crepe', categoryId: '113' },
  {
    id: '1561',
    name: 'Pão diet (de forma industrializado)',
    categoryId: '113',
  },
  {
    id: '1562',
    name: 'Pão light (de forma industrializado)',
    categoryId: '113',
  },
  { id: '1563', name: 'Pão de queijo light', categoryId: '113' },
  { id: '1564', name: 'Pão integral light', categoryId: '113' },
  {
    id: '1565',
    name: 'Tortas doces de qualquer sabor light',
    categoryId: '113',
  },
  {
    id: '1566',
    name: 'Tortas doces de qualquer sabor diet',
    categoryId: '113',
  },
  {
    id: '1567',
    name: 'Filhos (bolinho de farinha de trigo e ovos) light',
    categoryId: '113',
  },
  {
    id: '1568',
    name: 'Filhos (bolinho de farinha de trigo e ovos) diet',
    categoryId: '113',
  },
  { id: '1569', name: 'Bolo de chocolate light', categoryId: '113' },
  { id: '157', name: 'Vitamilho', categoryId: '102' },
  { id: '1570', name: 'Bolo de chocolate diet', categoryId: '113' },
  { id: '1571', name: 'Bolo de laranja light', categoryId: '113' },
  { id: '1572', name: 'Bolo de coco diet', categoryId: '113' },
  { id: '1573', name: 'Bolo de cenoura diet', categoryId: '113' },
  { id: '1574', name: 'Biscoito recheado light', categoryId: '113' },
  { id: '1575', name: 'Biscoito waffer light', categoryId: '113' },
  { id: '1576', name: 'Waffer (biscoito) light', categoryId: '113' },
  { id: '1577', name: 'Alfajores (biscoito) light', categoryId: '113' },
  { id: '1578', name: 'Bolacha recheada light', categoryId: '113' },
  { id: '1579', name: 'Biscoito recheado diet', categoryId: '113' },
  { id: '158', name: 'Creme de milho', categoryId: '102' },
  {
    id: '1580',
    name: 'Rosquinha recheada de qualquer sabor diet',
    categoryId: '113',
  },
  { id: '1581', name: 'Bolacha recheada diet', categoryId: '113' },
  { id: '1582', name: 'Pão doce diet', categoryId: '113' },
  { id: '1583', name: 'Pão de mel diet', categoryId: '113' },
  { id: '1584', name: 'Panetone diet', categoryId: '113' },
  { id: '1585', name: 'Biscoito salgado light', categoryId: '113' },
  { id: '1586', name: 'Bolacha salgada light', categoryId: '113' },
  { id: '1587', name: 'Chips (salgadinhos) light', categoryId: '113' },
  { id: '1588', name: 'Biscoito doce light', categoryId: '113' },
  { id: '1589', name: 'Bolacha doce light', categoryId: '113' },
  { id: '159', name: 'Sucrilhos de milho', categoryId: '102' },
  { id: '1590', name: 'Biscoito doce diet', categoryId: '113' },
  { id: '1591', name: 'Bolacha doce diet', categoryId: '113' },
  { id: '1592', name: 'Bolo de banana', categoryId: '113' },
  { id: '1593', name: 'Carne-seca', categoryId: '114' },
  { id: '16', name: 'Xerém de milho', categoryId: '100' },
  { id: '160', name: 'Cereal matinal de milho em flocos', categoryId: '102' },
  { id: '1600', name: 'Carne de charque', categoryId: '114' },
  { id: '1608', name: 'Jabá', categoryId: '114' },
  { id: '161', name: 'Germe de trigo', categoryId: '102' },
  { id: '1612', name: 'Carne de sol', categoryId: '114' },
  { id: '1618', name: 'Carne do sertão', categoryId: '114' },
  { id: '162', name: 'Fibra de trigo', categoryId: '102' },
  { id: '1621', name: 'Hambúrguer de carne bovina', categoryId: '114' },
  { id: '1628', name: 'Copa de porco defumada', categoryId: '114' },
  { id: '1629', name: 'Bacon', categoryId: '114' },
  { id: '163', name: 'Fibra de cereal trigo', categoryId: '102' },
  { id: '1630', name: 'Hambúrguer de frango', categoryId: '114' },
  { id: '1636', name: 'Salsicha no varejo', categoryId: '114' },
  { id: '164', name: 'Farinha de mandioca', categoryId: '102' },
  {
    id: '1648',
    name: 'Linguiça (suína, bovina, mista, etc.)',
    categoryId: '114',
  },
  { id: '165', name: 'Farinha de copioba', categoryId: '102' },
  { id: '1659', name: 'Linguiça de frango', categoryId: '114' },
  { id: '166', name: "Farinha d'água", categoryId: '102' },
  { id: '1664', name: 'Chouriço', categoryId: '114' },
  { id: '1665', name: 'Morcela', categoryId: '114' },
  { id: '1666', name: 'Morcilha', categoryId: '114' },
  { id: '1668', name: 'Paio', categoryId: '114' },
  { id: '1669', name: 'Mortadela', categoryId: '114' },
  { id: '167', name: 'Cruera', categoryId: '102' },
  { id: '1670', name: 'Salame', categoryId: '114' },
  { id: '1671', name: 'Salaminho', categoryId: '114' },
  { id: '1672', name: 'Blanquet de peru', categoryId: '114' },
  { id: '1673', name: 'Presunto', categoryId: '114' },
  { id: '1674', name: 'Hambúrguer de peru', categoryId: '114' },
  { id: '1677', name: 'Hambúrguer não especificado', categoryId: '114' },
  { id: '168', name: 'Goma de mandioca', categoryId: '102' },
  { id: '1682', name: 'Apresuntado', categoryId: '114' },
  { id: '1683', name: 'Pururuca de porco', categoryId: '114' },
  { id: '1684', name: 'Pele de porco preparada (pururuca)', categoryId: '114' },
  {
    id: '1685',
    name: 'Patê (fígado, calabresa, frango, presunto, etc.)',
    categoryId: '114',
  },
  { id: '1686', name: 'Carne de aves defumada', categoryId: '114' },
  { id: '1687', name: 'Carne salgada não especificada', categoryId: '114' },
  { id: '169', name: 'Sagu de mandioca', categoryId: '102' },
  { id: '1694', name: 'Mini chicken empanado', categoryId: '114' },
  { id: '1699', name: 'Mortadela light', categoryId: '114' },
  { id: '17', name: 'Amendoim (em grão) in natura', categoryId: '100' },
  { id: '170', name: 'Farinha de tapioca', categoryId: '102' },
  { id: '1700', name: 'Salsicha no varejo light', categoryId: '114' },
  { id: '1701', name: 'Salame light', categoryId: '114' },
  { id: '1702', name: 'Blanquet de peru light', categoryId: '114' },
  { id: '1703', name: 'Hambúrguer não especificado light', categoryId: '114' },
  { id: '1704', name: 'Refrigerante de cola tradicional', categoryId: '115' },
  { id: '1705', name: 'Coca-cola tradicional', categoryId: '115' },
  { id: '1706', name: 'Fanta laranja tradicional', categoryId: '115' },
  { id: '1707', name: 'Sukita tradicional', categoryId: '115' },
  {
    id: '1708',
    name: 'Refrigerante de guaraná tradicional',
    categoryId: '115',
  },
  { id: '1709', name: 'Guaraná tradicional', categoryId: '115' },
  { id: '171', name: 'Farinha beiju', categoryId: '102' },
  { id: '1710', name: 'Sprit refrigerante tradicional', categoryId: '115' },
  { id: '1711', name: 'Fanta uva tradicional', categoryId: '115' },
  { id: '1712', name: 'Refrigerante de cola light', categoryId: '115' },
  { id: '1713', name: 'Coca-cola light', categoryId: '115' },
  { id: '1714', name: 'Refrigerante de cola diet', categoryId: '115' },
  { id: '1715', name: 'Minuano tradicional', categoryId: '115' },
  { id: '1716', name: 'Mate tradicional', categoryId: '115' },
  { id: '1717', name: 'Bidu tradicional', categoryId: '115' },
  { id: '1718', name: 'Fanta laranja light', categoryId: '115' },
  { id: '1719', name: 'Refrigerante de guaraná light', categoryId: '115' },
  { id: '172', name: 'Sagu de tapioca', categoryId: '102' },
  { id: '1720', name: 'Guaraná light', categoryId: '115' },
  { id: '1721', name: 'Tubaína tradicional', categoryId: '115' },
  { id: '1722', name: 'Tubaína light', categoryId: '115' },
  { id: '1723', name: 'Caldo de cana', categoryId: '115' },
  { id: '1724', name: 'Garapá', categoryId: '115' },
  { id: '1725', name: 'Água de coco', categoryId: '115' },
  { id: '1726', name: 'Q-suco', categoryId: '115' },
  { id: '1727', name: 'Q-refresko', categoryId: '115' },
  { id: '1728', name: 'Nescafé', categoryId: '115' },
  { id: '1729', name: 'Erva-mate', categoryId: '115' },
  { id: '173', name: 'Tapioca de goma', categoryId: '102' },
  { id: '1730', name: 'Chimarrão', categoryId: '115' },
  { id: '1731', name: 'Tereré', categoryId: '115' },
  { id: '1732', name: 'Levedo de cerveja', categoryId: '115' },
  { id: '1733', name: 'Refrigerante não especificado', categoryId: '115' },
  { id: '1734', name: 'Cevada em pó', categoryId: '115' },
  { id: '1735', name: 'Chocomilk', categoryId: '115' },
  { id: '1736', name: 'Água tônica tradicional', categoryId: '115' },
  {
    id: '1737',
    name: 'Chá diet (preto, camomila, erva-cidreira, capim-limão, etc.)',
    categoryId: '115',
  },
  { id: '1738', name: 'Paraguai refrigerante tradicional', categoryId: '115' },
  { id: '1739', name: 'Gatorade', categoryId: '115' },
  { id: '174', name: 'Farinha láctea', categoryId: '102' },
  { id: '1740', name: 'Bebida energética', categoryId: '115' },
  {
    id: '1741',
    name: 'Chá (preto, camomila, erva-cidreira, capim-limão, etc.)',
    categoryId: '115',
  },
  { id: '1742', name: 'Café solúvel capuccino', categoryId: '115' },
  { id: '1743', name: 'Refrigerante de guaraná diet', categoryId: '115' },
  { id: '1744', name: 'Guaraná diet', categoryId: '115' },
  { id: '1745', name: 'Refrigerante de limão diet', categoryId: '115' },
  { id: '1746', name: 'Fanta uva light', categoryId: '115' },
  { id: '1747', name: 'Mate light', categoryId: '115' },
  { id: '1748', name: 'Água tônica light', categoryId: '115' },
  { id: '1749', name: 'Paraguai refrigerante light', categoryId: '115' },
  { id: '175', name: 'Neston', categoryId: '102' },
  { id: '1750', name: 'Q-suco light', categoryId: '115' },
  { id: '1751', name: 'Q-refresko light', categoryId: '115' },
  { id: '1752', name: 'Q-suco diet', categoryId: '115' },
  { id: '1753', name: 'Café capuccino solúvel light', categoryId: '115' },
  { id: '1754', name: 'Café capuccino solúvel diet', categoryId: '115' },
  { id: '1755', name: 'Água tônica diet', categoryId: '115' },
  { id: '1756', name: 'Refrigerante de quinino dietético', categoryId: '115' },
  { id: '1757', name: 'Chá mate orgânico', categoryId: '115' },
  { id: '1758', name: 'Chimarrão orgânico', categoryId: '115' },
  { id: '1759', name: 'Suco de clorofila', categoryId: '115' },
  { id: '176', name: 'Flocos de cereais', categoryId: '102' },
  { id: '1760', name: 'Café com farinha', categoryId: '115' },
  { id: '1761', name: 'Cerveja (com ou sem álcool)', categoryId: '116' },
  { id: '1762', name: 'Chopp', categoryId: '116' },
  { id: '1763', name: 'Aguardente', categoryId: '116' },
  { id: '1764', name: 'Cachaça', categoryId: '116' },
  { id: '1765', name: 'Batida de qualquer sabor', categoryId: '116' },
  { id: '1766', name: 'Rum', categoryId: '116' },
  { id: '1767', name: 'Vodka', categoryId: '116' },
  { id: '1768', name: 'Uísque', categoryId: '116' },
  { id: '1769', name: 'Whisky', categoryId: '116' },
  { id: '177', name: 'Vitaflocos', categoryId: '102' },
  { id: '1770', name: 'Champanhe', categoryId: '116' },
  { id: '1771', name: 'Sidra champanhe', categoryId: '116' },
  { id: '1772', name: 'Martini', categoryId: '116' },
  { id: '1773', name: 'Conhaque', categoryId: '116' },
  { id: '1774', name: 'Drink dreher', categoryId: '116' },
  { id: '1775', name: 'Licor de qualquer sabor', categoryId: '116' },
  { id: '1776', name: 'Cajuína', categoryId: '116' },
  { id: '1777', name: 'Vinho', categoryId: '116' },
  { id: '1778', name: 'Catuaba', categoryId: '116' },
  { id: '1779', name: 'Coquetel de frutas', categoryId: '116' },
  { id: '178', name: 'Mini pizza semipronta', categoryId: '102' },
  { id: '1780', name: 'Caipirinha', categoryId: '116' },
  { id: '1781', name: 'Bebida alcoólica', categoryId: '116' },
  { id: '1782', name: 'Vinho orgânico', categoryId: '116' },
  { id: '1783', name: 'Cerveja (com ou sem álcool) light', categoryId: '116' },
  { id: '1784', name: 'Caxiri (aguardente de mandioca)', categoryId: '116' },
  { id: '1785', name: 'Azeite de oliva', categoryId: '117' },
  { id: '1786', name: 'Óleo de soja', categoryId: '117' },
  { id: '1787', name: 'Banha suína', categoryId: '117' },
  { id: '1788', name: 'Banha bovina', categoryId: '117' },
  { id: '1789', name: 'Óleo não especificado', categoryId: '117' },
  { id: '1790', name: 'Óleo de dendê', categoryId: '117' },
  { id: '1791', name: 'Salgadinho', categoryId: '118' },
  {
    id: '1792',
    name: 'Pastel (queijo, carne, palmito, etc.)',
    categoryId: '118',
  },
  { id: '1793', name: 'Croquete', categoryId: '118' },
  { id: '1794', name: 'Coxinha', categoryId: '118' },
  {
    id: '1795',
    name: 'Empada (queijo, carne, camarão, etc.)',
    categoryId: '118',
  },
  {
    id: '1796',
    name: 'Rissole  (queijo, carne, camarão, etc.)',
    categoryId: '118',
  },
  { id: '1797', name: 'Acarajé', categoryId: '118' },
  { id: '1798', name: 'Torresmo', categoryId: '118' },
  { id: '1799', name: 'Quibe', categoryId: '118' },
  { id: '18', name: 'Ervilha em grão', categoryId: '100' },
  { id: '1800', name: 'Abará (Bahia)', categoryId: '118' },
  { id: '1801', name: 'Paçoca de carne de sol', categoryId: '118' },
  { id: '1802', name: 'Angu frito', categoryId: '118' },
  { id: '1803', name: 'Angu de milho', categoryId: '118' },
  { id: '1804', name: 'Polenta', categoryId: '118' },
  { id: '1805', name: 'Esfirra', categoryId: '118' },
  { id: '1806', name: 'Esfirra de carne', categoryId: '118' },
  { id: '1807', name: 'Esfirra de queijo', categoryId: '118' },
  { id: '1808', name: 'Esfirra de ricota', categoryId: '118' },
  { id: '1809', name: 'Esfirra de frango', categoryId: '118' },
  { id: '1810', name: 'Enroladinho', categoryId: '118' },
  { id: '1811', name: 'Bolinho de aipim', categoryId: '118' },
  { id: '1812', name: 'Bolinho de bacalhau', categoryId: '118' },
  { id: '1813', name: 'Cachorro-quente', categoryId: '118' },
  { id: '1814', name: 'Hambúrguer (sanduíche)', categoryId: '118' },
  { id: '1815', name: 'Cheeseburger', categoryId: '118' },
  { id: '1816', name: 'Eggsburger', categoryId: '118' },
  { id: '1817', name: 'Bauru', categoryId: '118' },
  { id: '1818', name: 'Americano', categoryId: '118' },
  { id: '1819', name: 'Misto-quente ou frio', categoryId: '118' },
  { id: '1820', name: 'Sanduíche de queijo prato', categoryId: '118' },
  { id: '1821', name: 'Sanduíche de salame', categoryId: '118' },
  { id: '1822', name: 'Sanduíche de presunto', categoryId: '118' },
  {
    id: '1823',
    name: 'Sanduíche de queijo prato com presunto',
    categoryId: '118',
  },
  { id: '1824', name: 'Sanduíche de mortadela', categoryId: '118' },
  { id: '1825', name: 'Sanduíche de queijo minas', categoryId: '118' },
  { id: '1826', name: 'Cheese egg', categoryId: '118' },
  { id: '1827', name: 'Cheese tudo', categoryId: '118' },
  { id: '1828', name: 'Sanduíche natural', categoryId: '118' },
  { id: '1829', name: 'Suco', categoryId: '118' },
  { id: '183', name: 'Fibra de soja', categoryId: '102' },
  { id: '1830', name: 'Suco de abacaxi', categoryId: '118' },
  { id: '1831', name: 'Suco de acerola', categoryId: '118' },
  { id: '1832', name: 'Suco de beterraba', categoryId: '118' },
  { id: '1833', name: 'Suco de cupuaçu', categoryId: '118' },
  { id: '1834', name: 'Suco de goiaba', categoryId: '118' },
  { id: '1835', name: 'Suco de laranja', categoryId: '118' },
  { id: '1836', name: 'Suco de laranja com banana', categoryId: '118' },
  { id: '1837', name: 'Suco de laranja e beterraba', categoryId: '118' },
  { id: '1838', name: 'Suco de laranja e cenoura', categoryId: '118' },
  {
    id: '1839',
    name: 'Suco de laranja cenoura e beterraba',
    categoryId: '118',
  },
  { id: '184', name: 'Minipastel', categoryId: '102' },
  { id: '1840', name: 'Suco de mamão', categoryId: '118' },
  { id: '1841', name: 'Suco de manga', categoryId: '118' },
  { id: '1842', name: 'Suco de maracujá', categoryId: '118' },
  { id: '1843', name: 'Suco de melão', categoryId: '118' },
  { id: '1844', name: 'Suco de morango', categoryId: '118' },
  { id: '1845', name: 'Suco de pêssego', categoryId: '118' },
  { id: '1846', name: 'Suco de pêssego em calda', categoryId: '118' },
  { id: '1847', name: 'Vitamina', categoryId: '118' },
  { id: '1848', name: 'Vitamina de banana', categoryId: '118' },
  { id: '1849', name: 'Vitamina de banana com aveia', categoryId: '118' },
  { id: '185', name: 'Macarrão', categoryId: '102' },
  { id: '1850', name: 'Vitamina de mamão', categoryId: '118' },
  { id: '1851', name: 'Vitamina de abacate', categoryId: '118' },
  { id: '1852', name: 'Vitamina de morango', categoryId: '118' },
  { id: '1853', name: 'Vitamina mista', categoryId: '118' },
  { id: '1854', name: 'Vitamina de maçã', categoryId: '118' },
  { id: '1855', name: 'Refresco', categoryId: '118' },
  { id: '1856', name: 'Refresco de caju', categoryId: '118' },
  { id: '1857', name: 'Refresco de groselha', categoryId: '118' },
  { id: '1858', name: 'Refresco de laranja', categoryId: '118' },
  { id: '1859', name: 'Refresco de maracujá', categoryId: '118' },
  { id: '1860', name: 'Refresco de limão', categoryId: '118' },
  {
    id: '1861',
    name: 'Salada ou verdura cozida, exceto de fruta',
    categoryId: '118',
  },
  { id: '1862', name: 'Salada de maionese', categoryId: '118' },
  { id: '1863', name: 'Pizza', categoryId: '118' },
  { id: '1864', name: 'Lasanha pronta light', categoryId: '118' },
  { id: '1865', name: 'Nhoque', categoryId: '118' },
  { id: '1866', name: 'Caneloni', categoryId: '118' },
  { id: '1867', name: 'Capeleti', categoryId: '118' },
  { id: '1868', name: 'Ravioli', categoryId: '118' },
  { id: '1869', name: 'Calzone', categoryId: '118' },
  { id: '1870', name: 'Panqueca', categoryId: '118' },
  { id: '1871', name: 'Pizza calabreza', categoryId: '118' },
  { id: '1872', name: 'Pizza muçarela', categoryId: '118' },
  { id: '1873', name: 'Pizza presunto', categoryId: '118' },
  { id: '1874', name: 'Pizza portuguesa', categoryId: '118' },
  { id: '1875', name: 'Macarronada', categoryId: '118' },
  { id: '1876', name: 'Galeto', categoryId: '118' },
  { id: '1877', name: 'Costela', categoryId: '118' },
  { id: '1878', name: 'Pipoca doce ou salgada', categoryId: '118' },
  { id: '1879', name: 'Café', categoryId: '118' },
  { id: '1880', name: 'Café com leite', categoryId: '118' },
  { id: '1881', name: 'Café tipo expresso', categoryId: '118' },
  { id: '1882', name: 'Café tipo capuccino', categoryId: '118' },
  { id: '1883', name: 'Milho cozido', categoryId: '118' },
  { id: '1884', name: 'Batata palito', categoryId: '118' },
  { id: '1885', name: 'Batata palha', categoryId: '118' },
  { id: '1886', name: 'Mungunzá', categoryId: '118' },
  { id: '1887', name: 'Canjica', categoryId: '118' },
  { id: '1888', name: 'Curau', categoryId: '118' },
  { id: '1889', name: 'Farofa', categoryId: '118' },
  {
    id: '1890',
    name: 'Mingau (fubá,  aveia, farinha, etc.)',
    categoryId: '118',
  },
  { id: '1891', name: 'Tacacá', categoryId: '118' },
  { id: '1892', name: 'Bolinho de coco', categoryId: '118' },
  { id: '1893', name: 'Risoto', categoryId: '118' },
  { id: '1894', name: 'Vatapá', categoryId: '118' },
  { id: '1895', name: 'Farofa pronta', categoryId: '118' },
  { id: '1896', name: 'Caldo de carne', categoryId: '118' },
  { id: '1897', name: 'Caldo-de-feijão', categoryId: '118' },
  { id: '1898', name: 'Caldo de mocotó', categoryId: '118' },
  { id: '1899', name: 'Baião de dois', categoryId: '118' },
  { id: '19', name: 'Fava (em grão)', categoryId: '100' },
  { id: '1900', name: 'Churrasco', categoryId: '118' },
  { id: '1901', name: 'Sushi', categoryId: '118' },
  { id: '1902', name: 'Salada de frutas', categoryId: '118' },
  { id: '1903', name: 'Sopa (legumes, carne, etc.)', categoryId: '118' },
  { id: '1904', name: 'Salpicão', categoryId: '118' },
  { id: '1905', name: 'Charuto de repolho', categoryId: '118' },
  { id: '1906', name: 'Arroz à grega', categoryId: '118' },
  { id: '1907', name: 'Arrumadinho', categoryId: '118' },
  { id: '1908', name: 'Bobó de camarão', categoryId: '118' },
  {
    id: '1909',
    name: 'Caruru (quiabo, amendoim, castanha de caju, camarão seco, etc.)',
    categoryId: '118',
  },
  { id: '1910', name: 'Cuscuz paulista', categoryId: '118' },
  {
    id: '1911',
    name: 'Empadão (queijo, frango, camarão, palmito, etc.)',
    categoryId: '118',
  },
  { id: '1912', name: 'Farofa de banana', categoryId: '118' },
  { id: '1913', name: 'Feijão-tropeiro', categoryId: '118' },
  { id: '1914', name: 'Galinha com arroz', categoryId: '118' },
  { id: '1915', name: 'Galinhada', categoryId: '118' },
  { id: '1916', name: 'Moqueca baiana', categoryId: '118' },
  { id: '1917', name: 'Omelete', categoryId: '118' },
  { id: '1918', name: 'Pirão', categoryId: '118' },
  { id: '1919', name: 'Quibebe', categoryId: '118' },
  { id: '1920', name: 'Quiche', categoryId: '118' },
  { id: '1921', name: 'Suflê', categoryId: '118' },
  { id: '1922', name: 'Tutu', categoryId: '118' },
  { id: '1923', name: 'Moqueca capixaba', categoryId: '118' },
  { id: '1924', name: 'Maniçoba', categoryId: '118' },
  { id: '1925', name: 'Caldo verde', categoryId: '118' },
  { id: '1926', name: 'Arroz de cuxá', categoryId: '118' },
  { id: '1927', name: 'Angu à baiana', categoryId: '118' },
  { id: '1928', name: 'Chocolate', categoryId: '118' },
  { id: '1929', name: 'Gemada', categoryId: '118' },
  { id: '1930', name: 'Açaí com granola', categoryId: '118' },
  { id: '1931', name: 'Suco orgânico', categoryId: '118' },
  { id: '1932', name: 'Suco de abacaxi orgânico', categoryId: '118' },
  { id: '1933', name: 'Suco de acerola orgânico', categoryId: '118' },
  { id: '1934', name: 'Suco de goiaba orgânico', categoryId: '118' },
  { id: '1935', name: 'Suco de laranja orgânico', categoryId: '118' },
  {
    id: '1936',
    name: 'Suco de laranja cenoura e beterraba orgânico',
    categoryId: '118',
  },
  { id: '1937', name: 'Suco de manga orgânico', categoryId: '118' },
  { id: '1938', name: 'Suco de maracujá orgânico', categoryId: '118' },
  { id: '1939', name: 'Suco de morango orgânico', categoryId: '118' },
  { id: '1940', name: 'Suco de pêssego orgânico', categoryId: '118' },
  { id: '1941', name: 'Suco de pêssego em calda orgânico', categoryId: '118' },
  { id: '1942', name: 'Pizza pronta light', categoryId: '118' },
  { id: '1944', name: 'Macarrão pronto light', categoryId: '118' },
  { id: '1945', name: 'Pizza portuguesa light', categoryId: '118' },
  { id: '1946', name: 'Farofa pronta light em pacote', categoryId: '118' },
  { id: '1947', name: 'Vaca atolada', categoryId: '118' },
  {
    id: '1948',
    name: 'Salada ou verdura crua, exceto de fruta',
    categoryId: '118',
  },
  { id: '1949', name: 'Outros legumes cozidos', categoryId: '118' },
  { id: '1950', name: 'Café da manha', categoryId: '118' },
  { id: '1951', name: 'Prato de comida brasileira', categoryId: '118' },
  { id: '1952', name: 'Prato de comida do nordeste', categoryId: '118' },
  { id: '1953', name: 'Prato de comida do norte', categoryId: '118' },
  { id: '1954', name: 'Prato de comida do sudeste', categoryId: '118' },
  { id: '1955', name: 'Prato de comida do sul', categoryId: '118' },
  { id: '1956', name: 'Prato de comida do centro-oeste', categoryId: '118' },
  { id: '1957', name: 'Arroz com feijão', categoryId: '118' },
  { id: '1958', name: 'Pão com manteiga', categoryId: '118' },
  { id: '1959', name: 'Pão com margarina', categoryId: '118' },
  { id: '1960', name: 'Pão com ovo', categoryId: '118' },
  {
    id: '1961',
    name: 'Carne com batata, inhame, batata-baroa ou aipim',
    categoryId: '118',
  },
  {
    id: '1962',
    name: 'Carne com legumes (exceto batata, inhame e aipim)',
    categoryId: '118',
  },
  {
    id: '1963',
    name: 'Frango com batata, inhame batata-baroa ou aipim',
    categoryId: '118',
  },
  {
    id: '1964',
    name: 'Frango com legumes (exceto batata, inhame e aipim)',
    categoryId: '118',
  },
  { id: '1965', name: 'Abobora com quiabo', categoryId: '118' },
  { id: '1966', name: 'Arroz carreteiro', categoryId: '118' },
  { id: '1967', name: 'Maria izabel', categoryId: '118' },
  { id: '1968', name: 'Arroz de leite', categoryId: '118' },
  { id: '1969', name: 'Arroz com mandioca', categoryId: '118' },
  { id: '1970', name: 'Arroz com ovo', categoryId: '118' },
  { id: '1971', name: 'Palma', categoryId: '118' },
  {
    id: '2',
    name: 'Arroz (polido, parboilizado, agulha, agulhinha, etc.)',
    categoryId: '100',
  },
  { id: '20', name: 'Mangalô amargo em grão', categoryId: '100' },
  { id: '200', name: 'Purê de batata', categoryId: '102' },
  { id: '201', name: 'Bife vegetal', categoryId: '102' },
  { id: '202', name: 'Carne vegetal', categoryId: '102' },
  { id: '203', name: 'Pasta de soja', categoryId: '102' },
  { id: '204', name: 'Carne de soja', categoryId: '102' },
  { id: '205', name: 'Amendoim moído', categoryId: '102' },
  { id: '206', name: 'Granola', categoryId: '102' },
  { id: '207', name: 'Musli', categoryId: '102' },
  { id: '208', name: 'Mix de cereais', categoryId: '102' },
  { id: '209', name: 'Miojo', categoryId: '102' },
  { id: '21', name: 'Feijão-de-corda', categoryId: '100' },
  { id: '210', name: 'Macarrão instantâneo', categoryId: '102' },
  { id: '211', name: 'Sustagem', categoryId: '102' },
  { id: '212', name: 'Proteína de soja', categoryId: '102' },
  { id: '213', name: 'Proteína vegetal', categoryId: '102' },
  {
    id: '214',
    name: 'Complemento alimentar de qualquer sabor',
    categoryId: '102',
  },
  { id: '215', name: 'Sucrilhos de milho light', categoryId: '102' },
  { id: '216', name: 'Mini pizza semipronta light', categoryId: '102' },
  { id: '217', name: 'Macarrão instantâneo light', categoryId: '102' },
  { id: '219', name: 'Proteína de soja orgânica', categoryId: '102' },
  { id: '22', name: 'Feijão-verde', categoryId: '100' },
  { id: '220', name: 'Macarrão com carne', categoryId: '102' },
  { id: '221', name: 'Macarrão com peixe', categoryId: '102' },
  { id: '222', name: 'Coco-da-baía (seco ou verde)', categoryId: '103' },
  { id: '223', name: 'Castanha portuguesa', categoryId: '103' },
  { id: '224', name: 'Pinhão', categoryId: '103' },
  { id: '225', name: 'Amêndoa', categoryId: '103' },
  { id: '226', name: 'Avelã', categoryId: '103' },
  { id: '227', name: 'Castanha-do-pará', categoryId: '103' },
  { id: '228', name: 'Castanha de caju', categoryId: '103' },
  { id: '229', name: 'Butiá', categoryId: '103' },
  { id: '23', name: 'Semente de linhaça', categoryId: '100' },
  { id: '230', name: 'Tucumã', categoryId: '103' },
  { id: '231', name: 'Coco de mucajá', categoryId: '103' },
  { id: '232', name: 'Noz (nogueira)', categoryId: '103' },
  { id: '233', name: 'Açaí', categoryId: '103' },
  { id: '234', name: 'Juçara', categoryId: '103' },
  { id: '235', name: 'Uaçaí', categoryId: '103' },
  { id: '236', name: 'Jussara', categoryId: '103' },
  { id: '237', name: 'Pupunha', categoryId: '103' },
  { id: '238', name: 'Bacaba', categoryId: '103' },
  { id: '239', name: 'Bacabuçu', categoryId: '103' },
  { id: '24', name: 'Andu', categoryId: '100' },
  { id: '240', name: 'Castanha-da-índia', categoryId: '103' },
  { id: '241', name: 'Pistache', categoryId: '103' },
  { id: '242', name: 'Buriti', categoryId: '103' },
  { id: '243', name: 'Coco', categoryId: '103' },
  { id: '244', name: 'Patauá', categoryId: '103' },
  { id: '245', name: 'Alface', categoryId: '104' },
  { id: '246', name: 'Bertalha', categoryId: '104' },
  { id: '247', name: 'Chicória', categoryId: '104' },
  { id: '25', name: 'Grão de bico', categoryId: '100' },
  { id: '251', name: 'Escarola', categoryId: '104' },
  { id: '252', name: 'Couve', categoryId: '104' },
  { id: '26', name: 'Lentilha', categoryId: '100' },
  { id: '263', name: 'Couve-flor', categoryId: '104' },
  { id: '27', name: 'Soja em grão', categoryId: '100' },
  { id: '270', name: 'Espinafre', categoryId: '104' },
  { id: '275', name: 'Mostarda (verdura)', categoryId: '104' },
  { id: '279', name: 'Repolho', categoryId: '104' },
  {
    id: '28',
    name: 'Feijão (preto, mulatinho, roxo, rosinha, etc.)',
    categoryId: '100',
  },
  { id: '289', name: 'Cebolinha', categoryId: '104' },
  { id: '29', name: 'Quirera não especificada', categoryId: '100' },
  { id: '290', name: 'Agrião', categoryId: '104' },
  { id: '295', name: 'Taioba', categoryId: '104' },
  { id: '298', name: 'Acelga', categoryId: '104' },
  { id: '3', name: 'Milho (em grão)', categoryId: '100' },
  { id: '30', name: 'Feijão-verde orgânico', categoryId: '100' },
  { id: '302', name: 'Beterraba branca (acelga)', categoryId: '104' },
  { id: '303', name: 'Almeirão', categoryId: '104' },
  { id: '307', name: 'Radite', categoryId: '104' },
  { id: '31', name: 'Feijão orgânico', categoryId: '100' },
  { id: '310', name: 'Brócolis', categoryId: '104' },
  { id: '317', name: 'Serralha', categoryId: '104' },
  { id: '32', name: 'Pipoca  light', categoryId: '100' },
  { id: '320', name: 'Caruru', categoryId: '104' },
  { id: '321', name: 'Cuxá', categoryId: '104' },
  { id: '322', name: 'Vinagreira', categoryId: '104' },
  { id: '323', name: 'Cariru', categoryId: '104' },
  { id: '324', name: 'Rúcula', categoryId: '104' },
  { id: '325', name: 'Jambu', categoryId: '104' },
  { id: '326', name: 'Língua de vaca (verdura)', categoryId: '104' },
  { id: '327', name: 'Alcachofra', categoryId: '104' },
  { id: '328', name: 'Bredo', categoryId: '104' },
  { id: '329', name: 'Salsão (aipo)', categoryId: '104' },
  { id: '33', name: 'Arroz  orgânico', categoryId: '100' },
  { id: '330', name: 'Erva-doce', categoryId: '104' },
  { id: '331', name: 'Folha de aipim', categoryId: '104' },
  { id: '332', name: 'Folha de macaxeira', categoryId: '104' },
  { id: '333', name: 'Broto de feijão', categoryId: '104' },
  { id: '335', name: 'Moranga', categoryId: '104' },
  { id: '339', name: 'Abobrinha', categoryId: '104' },
  { id: '34', name: 'Arroz integral orgânico', categoryId: '100' },
  { id: '347', name: 'Jerimum', categoryId: '104' },
  { id: '349', name: 'Abóbora', categoryId: '104' },
  { id: '35', name: 'Feijão-de-soja orgânico', categoryId: '100' },
  { id: '358', name: 'Pépino', categoryId: '104' },
  { id: '359', name: 'Chuchu', categoryId: '104' },
  { id: '36', name: 'Quinoa', categoryId: '100' },
  { id: '368', name: 'Jiló', categoryId: '104' },
  { id: '37', name: 'Batata-inglesa', categoryId: '101' },
  { id: '376', name: 'Maxixe', categoryId: '104' },
  { id: '380', name: 'Pepininho (maxixe)', categoryId: '104' },
  { id: '382', name: 'Palmito in natura', categoryId: '104' },
  { id: '386', name: 'Guariroba (palmito in natura)', categoryId: '104' },
  { id: '389', name: 'Gueroba (palmito in natura)', categoryId: '104' },
  { id: '391', name: 'Pimentão', categoryId: '104' },
  { id: '392', name: 'Quiabo', categoryId: '104' },
  { id: '393', name: 'Quiabo', categoryId: '104' },
  { id: '399', name: 'Tomate', categoryId: '104' },
  { id: '400', name: 'Vagem', categoryId: '104' },
  { id: '406', name: 'Cogumelo in natura', categoryId: '104' },
  { id: '407', name: 'Berinjela', categoryId: '104' },
  { id: '413', name: 'Berinjela', categoryId: '104' },
  { id: '416', name: 'Ervilha em vagem', categoryId: '104' },
  { id: '418', name: 'Cebola', categoryId: '104' },
  { id: '428', name: 'Catalonha', categoryId: '104' },
  { id: '429', name: 'Jardineira (seleta)', categoryId: '104' },
  { id: '430', name: 'Seleta (jardineira)', categoryId: '104' },
  { id: '431', name: 'Alho', categoryId: '104' },
  { id: '432', name: 'Alho-poró', categoryId: '104' },
  { id: '433', name: 'Broto de alfafa', categoryId: '104' },
  { id: '434', name: 'Alface orgânica', categoryId: '104' },
  { id: '435', name: 'Tomate orgânico', categoryId: '104' },
  { id: '436', name: 'Pimentão orgânico', categoryId: '104' },
  { id: '437', name: 'Orégano', categoryId: '104' },
  { id: '438', name: 'Pacová', categoryId: '105' },
  {
    id: '439',
    name: 'Banana (ouro, prata, d´água, da terra, etc.)',
    categoryId: '105',
  },
  {
    id: '449',
    name: 'Laranja (pera, seleta, lima, da terra, etc.)',
    categoryId: '105',
  },
  { id: '450', name: 'Lima', categoryId: '105' },
  { id: '451', name: 'Limão (comum, galego, etc.)', categoryId: '105' },
  { id: '452', name: 'Tangerina', categoryId: '105' },
  { id: '453', name: 'Mexerica', categoryId: '105' },
  { id: '454', name: 'Bergamota', categoryId: '105' },
  { id: '455', name: 'Mimosa', categoryId: '105' },
  { id: '456', name: 'Tanja', categoryId: '105' },
  { id: '457', name: 'Maricota', categoryId: '105' },
  { id: '458', name: 'Laranjinha japonesa', categoryId: '105' },
  { id: '459', name: 'Cana-de-açúcar', categoryId: '105' },
  { id: '460', name: 'Abacaxi', categoryId: '105' },
  { id: '461', name: 'Ananás', categoryId: '105' },
  { id: '462', name: 'Abacate', categoryId: '105' },
  { id: '463', name: 'Caqui', categoryId: '105' },
  { id: '464', name: 'Figo', categoryId: '105' },
  { id: '465', name: 'Maçã', categoryId: '105' },
  { id: '466', name: 'Mamão', categoryId: '105' },
  { id: '467', name: 'Papaia', categoryId: '105' },
  { id: '468', name: 'Manga', categoryId: '105' },
  { id: '469', name: 'Manguito', categoryId: '105' },
  { id: '470', name: 'Maracujá', categoryId: '105' },
  { id: '471', name: 'Melancia', categoryId: '105' },
  { id: '472', name: 'Melão', categoryId: '105' },
  { id: '473', name: 'pera', categoryId: '105' },
  { id: '474', name: 'Pêssego', categoryId: '105' },
  { id: '475', name: 'Fruta-de-conde', categoryId: '105' },
  { id: '476', name: 'Pinha (fruta-de-conde)', categoryId: '105' },
  { id: '477', name: 'Ata', categoryId: '105' },
  { id: '478', name: 'Uva', categoryId: '105' },
  { id: '479', name: 'Uva passa', categoryId: '105' },
  { id: '480', name: 'Jenipapo', categoryId: '105' },
  { id: '481', name: 'Jaca', categoryId: '105' },
  { id: '482', name: 'Goiaba', categoryId: '105' },
  { id: '483', name: 'Araçá-açu (goiaba)', categoryId: '105' },
  { id: '484', name: 'Ameixa', categoryId: '105' },
  { id: '485', name: 'Caju', categoryId: '105' },
  { id: '486', name: 'Cereja', categoryId: '105' },
  { id: '487', name: 'Cajá-manga', categoryId: '105' },
  { id: '488', name: 'Cajarana', categoryId: '105' },
  { id: '489', name: 'Taperebá', categoryId: '105' },
  { id: '490', name: 'Acaja (taberebá)', categoryId: '105' },
  { id: '491', name: 'Carambola', categoryId: '105' },
  { id: '492', name: 'Jabuticaba', categoryId: '105' },
  { id: '493', name: 'Graviola', categoryId: '105' },
  { id: '494', name: 'Morango', categoryId: '105' },
  { id: '495', name: 'Jambo', categoryId: '105' },
  { id: '496', name: 'Atemoia', categoryId: '105' },
  { id: '497', name: 'Mangaba', categoryId: '105' },
  { id: '498', name: 'Araçá', categoryId: '105' },
  { id: '499', name: 'Nêspera', categoryId: '105' },
  { id: '50', name: 'Mandioquinha salsa (batata-baroa)', categoryId: '101' },
  { id: '500', name: 'Fruta-pão', categoryId: '105' },
  { id: '501', name: 'Sapoti', categoryId: '105' },
  { id: '502', name: 'Uxi', categoryId: '105' },
  { id: '503', name: 'Tamarindo', categoryId: '105' },
  { id: '504', name: 'Cacau', categoryId: '105' },
  { id: '505', name: 'Pitomba', categoryId: '105' },
  { id: '506', name: 'Bacuri', categoryId: '105' },
  { id: '507', name: 'Ingá', categoryId: '105' },
  { id: '508', name: 'Pequi', categoryId: '105' },
  { id: '509', name: 'Pitanga', categoryId: '105' },
  { id: '510', name: 'Ciriguela', categoryId: '105' },
  { id: '511', name: 'Murici', categoryId: '105' },
  { id: '512', name: 'Umbu', categoryId: '105' },
  { id: '513', name: 'Imbu', categoryId: '105' },
  { id: '514', name: 'Biribá', categoryId: '105' },
  { id: '515', name: 'Cupuaçu', categoryId: '105' },
  { id: '516', name: 'Nectarina', categoryId: '105' },
  { id: '517', name: 'Mari', categoryId: '105' },
  { id: '518', name: 'Romã', categoryId: '105' },
  { id: '519', name: 'Acerola', categoryId: '105' },
  { id: '520', name: 'Kiwi', categoryId: '105' },
  { id: '521', name: 'Abiu', categoryId: '105' },
  { id: '522', name: 'Jurubeba', categoryId: '105' },
  { id: '523', name: 'Fruta (não especificada)', categoryId: '105' },
  { id: '524', name: 'Maçã orgânica', categoryId: '105' },
  { id: '525', name: 'Acerola orgânica', categoryId: '105' },
  { id: '526', name: 'Amora', categoryId: '105' },
  { id: '527', name: 'Jamelão (jamburão)', categoryId: '105' },
  { id: '528', name: 'Demerara', categoryId: '106' },
  { id: '529', name: 'Açúcar mascavo', categoryId: '106' },
  { id: '530', name: 'Rapadura', categoryId: '106' },
  { id: '531', name: 'Alfenim de cana', categoryId: '106' },
  { id: '532', name: 'Batida (rapadura)', categoryId: '106' },
  {
    id: '533',
    name: 'Sorvete de qualquer sabor industrializado',
    categoryId: '106',
  },
  {
    id: '534',
    name: 'Picolé de qualquer sabor industrializado',
    categoryId: '106',
  },
  { id: '535', name: 'Chiclete', categoryId: '106' },
  { id: '536', name: 'Bala', categoryId: '106' },
  { id: '537', name: 'Caramelo (bala)', categoryId: '106' },
  { id: '538', name: 'Drops', categoryId: '106' },
  { id: '539', name: 'Pastilha', categoryId: '106' },
  { id: '54', name: 'Cenoura amarela (batata-baroa)', categoryId: '101' },
  { id: '540', name: 'Pirulito', categoryId: '106' },
  { id: '541', name: 'Goma de mascar', categoryId: '106' },
  { id: '542', name: 'Jujuba', categoryId: '106' },
  { id: '543', name: 'Tablete de chocolate', categoryId: '106' },
  { id: '544', name: 'Barra de chocolate', categoryId: '106' },
  { id: '545', name: 'Confete', categoryId: '106' },
  { id: '546', name: 'Chocolate em pó de qualquer marca', categoryId: '106' },
  { id: '547', name: 'Ovomaltine', categoryId: '106' },
  { id: '548', name: 'Achocolatado em pó', categoryId: '106' },
  { id: '549', name: 'Toddynho', categoryId: '106' },
  { id: '55', name: 'Batata-doce', categoryId: '101' },
  { id: '550', name: 'Bombom de qualquer marca', categoryId: '106' },
  { id: '551', name: 'Trufa', categoryId: '106' },
  {
    id: '552',
    name: 'Geleia de frutas de qualquer marca ou sabor',
    categoryId: '106',
  },
  { id: '553', name: 'Mousse de qualquer sabor (Geleia)', categoryId: '106' },
  { id: '554', name: 'Geleia de mocotó', categoryId: '106' },
  {
    id: '555',
    name: 'Doce de frutas em pasta de qualquer sabor',
    categoryId: '106',
  },
  { id: '556', name: 'Pasta de amendoim', categoryId: '106' },
  { id: '557', name: 'Pessegada', categoryId: '106' },
  { id: '558', name: 'Marmelada', categoryId: '106' },
  { id: '559', name: 'Figada', categoryId: '106' },
  { id: '560', name: 'Goiabada', categoryId: '106' },
  { id: '561', name: 'Caju em pasta', categoryId: '106' },
  { id: '562', name: 'Mariola', categoryId: '106' },
  {
    id: '563',
    name: 'Doce de frutas em calda de qualquer sabor',
    categoryId: '106',
  },
  {
    id: '564',
    name: 'Doce de frutas cristalizado de qualquer sabor',
    categoryId: '106',
  },
  { id: '565', name: 'Melado', categoryId: '106' },
  { id: '566', name: 'Mel', categoryId: '106' },
  { id: '567', name: 'Gelatina de qualquer sabor', categoryId: '106' },
  { id: '568', name: 'Adoçante artificial', categoryId: '106' },
  { id: '569', name: 'Merengue', categoryId: '106' },
  { id: '570', name: 'Schimier de cana', categoryId: '106' },
  { id: '571', name: 'Fruta seca ou desidratada', categoryId: '106' },
  { id: '572', name: 'Passa', categoryId: '106' },
  { id: '573', name: 'Pudim de qualquer sabor', categoryId: '106' },
  { id: '574', name: 'Danette pudim', categoryId: '106' },
  { id: '575', name: 'Manjar', categoryId: '106' },
  { id: '576', name: 'Cuscuz', categoryId: '106' },
  { id: '577', name: 'Cuscuz de tapioca', categoryId: '106' },
  { id: '578', name: 'Maria-mole', categoryId: '106' },
  { id: '579', name: 'Cocada', categoryId: '106' },
  { id: '580', name: 'Quebra-queixo', categoryId: '106' },
  { id: '581', name: 'Doce de amendoim', categoryId: '106' },
  { id: '582', name: 'Pé de moleque', categoryId: '106' },
  { id: '583', name: 'Paçoca', categoryId: '106' },
  { id: '584', name: 'Torrão de amendoim', categoryId: '106' },
  { id: '585', name: 'Paçoquinha de amendoim', categoryId: '106' },
  { id: '586', name: 'Amendoim caramelizado', categoryId: '106' },
  { id: '587', name: 'Amendoim amanteigado', categoryId: '106' },
  { id: '588', name: 'Amendoim achocolatado', categoryId: '106' },
  { id: '589', name: 'Amendoim apimentado', categoryId: '106' },
  { id: '590', name: 'Amendoim cozido', categoryId: '106' },
  { id: '591', name: 'Brigadeiro', categoryId: '106' },
  { id: '592', name: 'Bomba de qualquer tipo', categoryId: '106' },
  { id: '593', name: 'Mil folhas', categoryId: '106' },
  { id: '594', name: 'Queijadinha', categoryId: '106' },
  { id: '595', name: 'Doce à base de ovos', categoryId: '106' },
  { id: '596', name: 'Caçarola italiana', categoryId: '106' },
  { id: '597', name: 'Quindim', categoryId: '106' },
  { id: '598', name: 'Fios de ovos', categoryId: '106' },
  { id: '599', name: 'Doce à base de leite', categoryId: '106' },
  { id: '600', name: 'Pavê de qualquer sabor', categoryId: '106' },
  { id: '601', name: 'Ambrosia', categoryId: '106' },
  { id: '602', name: 'Leite geleificado', categoryId: '106' },
  { id: '603', name: 'Chandele de qualquer sabor', categoryId: '106' },
  { id: '604', name: 'Mumu', categoryId: '106' },
  { id: '605', name: 'Canudinho recheado', categoryId: '106' },
  { id: '606', name: 'Sarolho', categoryId: '106' },
  { id: '607', name: 'Beiju', categoryId: '106' },
  { id: '608', name: 'Schimier de fruta (exceto de cana)', categoryId: '106' },
  { id: '609', name: 'Beijo de moça', categoryId: '106' },
  { id: '610', name: 'Picolé ensacado', categoryId: '106' },
  { id: '611', name: 'Geladinho', categoryId: '106' },
  { id: '612', name: 'Churro', categoryId: '106' },
  { id: '613', name: 'Pamonha', categoryId: '106' },
  { id: '614', name: 'Algodão-doce', categoryId: '106' },
  { id: '615', name: 'Io-Iô crem (chocolate em creme)', categoryId: '106' },
  { id: '616', name: 'Ovo de páscoa', categoryId: '106' },
  { id: '617', name: 'Kinder ovo', categoryId: '106' },
  { id: '618', name: 'Torrone', categoryId: '106' },
  { id: '619', name: 'Arroz-doce', categoryId: '106' },
  { id: '62', name: 'Inhame', categoryId: '101' },
  { id: '620', name: 'Polpa de coco', categoryId: '106' },
  { id: '621', name: 'Diet shake', categoryId: '106' },
  { id: '622', name: 'Concentrado alimentar diet shake', categoryId: '106' },
  { id: '623', name: 'Açúcar', categoryId: '106' },
  { id: '624', name: 'Açúcar light', categoryId: '106' },
  { id: '625', name: 'Barra de cereais', categoryId: '106' },
  { id: '626', name: 'Barra de cereais salgada', categoryId: '106' },
  { id: '627', name: 'Barra de cereais doce', categoryId: '106' },
  {
    id: '628',
    name: 'Sobremesa de qualquer tipo (exceto infantil)',
    categoryId: '106',
  },
  { id: '629', name: 'Rabanada', categoryId: '106' },
  { id: '630', name: 'Milk shake', categoryId: '106' },
  { id: '631', name: 'Geleia diet', categoryId: '106' },
  { id: '632', name: 'Doce de frutas diet', categoryId: '106' },
  { id: '633', name: 'Pastéis de santa clara', categoryId: '106' },
  { id: '634', name: 'Suspiro', categoryId: '106' },
  {
    id: '635',
    name: 'Doce de frutas cristalizado de qualquer sabor diet',
    categoryId: '106',
  },
  {
    id: '636',
    name: 'Sorvete de qualquer sabor industrializado light',
    categoryId: '106',
  },
  {
    id: '637',
    name: 'Sorvete de qualquer sabor industrializado diet',
    categoryId: '106',
  },
  { id: '638', name: 'Bala light', categoryId: '106' },
  { id: '639', name: 'Chiclete diet', categoryId: '106' },
  { id: '640', name: 'Bala diet', categoryId: '106' },
  { id: '641', name: 'Barra de chocolate light', categoryId: '106' },
  { id: '642', name: 'Barra de chocolate diet', categoryId: '106' },
  { id: '643', name: 'Achocolatado em pó light', categoryId: '106' },
  { id: '644', name: 'Achocolatado em pó diet', categoryId: '106' },
  { id: '645', name: 'Toddynho diet', categoryId: '106' },
  { id: '646', name: 'Bombom de qualquer marca light', categoryId: '106' },
  { id: '647', name: 'Bombom de qualquer marca diet', categoryId: '106' },
  {
    id: '648',
    name: 'Bombom caramelizado de qualquer marca diet',
    categoryId: '106',
  },
  {
    id: '649',
    name: 'Geleia de frutas de qualquer marca ou sabor light',
    categoryId: '106',
  },
  { id: '650', name: 'Geleia light', categoryId: '106' },
  { id: '651', name: 'Geleia de frutas light', categoryId: '106' },
  {
    id: '652',
    name: 'Doce de frutas em barra ou pasta light',
    categoryId: '106',
  },
  { id: '653', name: 'Doce de frutas em pasta light', categoryId: '106' },
  { id: '654', name: 'Pudim de qualquer sabor light', categoryId: '106' },
  { id: '655', name: 'Pudim danette light', categoryId: '106' },
  { id: '656', name: 'Pudim de qualquer sabor diet', categoryId: '106' },
  { id: '657', name: 'Doce de leite light', categoryId: '106' },
  { id: '658', name: 'Doce de leite diet', categoryId: '106' },
  { id: '659', name: 'Barra de cereais diet', categoryId: '106' },
  { id: '660', name: 'Barra de cereais doce diet', categoryId: '106' },
  { id: '661', name: 'Milk shake diet', categoryId: '106' },
  { id: '662', name: 'Cocada diet', categoryId: '106' },
  { id: '663', name: 'Doce de amendoim diet', categoryId: '106' },
  { id: '664', name: 'Paçoca diet', categoryId: '106' },
  { id: '665', name: 'Amendoim amanteigado diet', categoryId: '106' },
  { id: '666', name: 'Doce à base de leite diet', categoryId: '106' },
  { id: '667', name: 'Gelatina de qualquer sabor light', categoryId: '106' },
  { id: '668', name: 'Adoçante light', categoryId: '106' },
  { id: '669', name: 'Adoçante em pó light', categoryId: '106' },
  { id: '670', name: 'Adoçante liquido light', categoryId: '106' },
  { id: '671', name: 'Mostarda molho', categoryId: '107' },
  { id: '672', name: 'Hortelã', categoryId: '107' },
  { id: '673', name: 'Alcaparra em conserva', categoryId: '107' },
  { id: '674', name: 'Coentro', categoryId: '107' },
  { id: '675', name: 'Molho de soja', categoryId: '107' },
  { id: '676', name: 'Shoyo', categoryId: '107' },
  { id: '677', name: 'Leite de coco', categoryId: '107' },
  { id: '678', name: 'Maionese (molho)', categoryId: '107' },
  { id: '679', name: 'Massa de tomate', categoryId: '107' },
  { id: '680', name: 'Molho de tomate', categoryId: '107' },
  { id: '681', name: 'Ketchup', categoryId: '107' },
  { id: '682', name: 'Catchup', categoryId: '107' },
  { id: '683', name: 'Pimenta em pó', categoryId: '107' },
  { id: '684', name: 'Tucupi em caldo sem pimenta', categoryId: '107' },
  { id: '685', name: 'Creme de queijo', categoryId: '107' },
  { id: '686', name: 'Caldo de peixe', categoryId: '107' },
  { id: '687', name: 'Caldo de tomate', categoryId: '107' },
  { id: '688', name: 'Gergelim', categoryId: '107' },
  { id: '689', name: 'Tomate seco', categoryId: '107' },
  { id: '69', name: 'Quicaré', categoryId: '101' },
  { id: '690', name: 'Maionese (molho) light', categoryId: '107' },
  { id: '691', name: 'Molho de soja light', categoryId: '107' },
  { id: '692', name: 'Leite de coco light', categoryId: '107' },
  { id: '693', name: 'Vinagrete', categoryId: '107' },
  { id: '694', name: 'Filé-mignon', categoryId: '108' },
  { id: '70', name: 'Mandioca', categoryId: '101' },
  { id: '704', name: 'Contrafilé', categoryId: '108' },
  { id: '711', name: 'Bisteca bovina', categoryId: '108' },
  { id: '719', name: 'Alcatra', categoryId: '108' },
  { id: '720', name: 'Alcatra', categoryId: '108' },
  { id: '729', name: 'Maminha', categoryId: '108' },
  { id: '733', name: 'Picanha', categoryId: '108' },
  { id: '736', name: 'Picanha', categoryId: '108' },
  { id: '738', name: 'Patinho', categoryId: '108' },
  { id: '745', name: 'Cabeça de lombo (carne bovina)', categoryId: '108' },
  { id: '751', name: 'Posta branca', categoryId: '108' },
  { id: '754', name: 'Tatu (lagarto redondo)', categoryId: '108' },
  { id: '758', name: 'Paulista', categoryId: '108' },
  { id: '760', name: 'Lombo paulista (carne bovina)', categoryId: '108' },
  { id: '764', name: 'Posta vermelha', categoryId: '108' },
  { id: '765', name: 'Acém', categoryId: '108' },
  { id: '771', name: 'Agulha (acém)', categoryId: '108' },
  { id: '774', name: 'Paleta', categoryId: '108' },
  { id: '778', name: 'Pá com osso', categoryId: '108' },
  { id: '781', name: 'Músculo bovino', categoryId: '108' },
  { id: '786', name: 'Chambaril', categoryId: '108' },
  { id: '789', name: 'Carne marica bovina', categoryId: '108' },
  { id: '792', name: 'Vazio (carne bovina)', categoryId: '108' },
  { id: '795', name: 'Peito bovino', categoryId: '108' },
  { id: '797', name: 'Fraldinha (capa de filé)', categoryId: '108' },
  { id: '80', name: 'Aipim', categoryId: '101' },
  { id: '801', name: 'Aba de filé', categoryId: '108' },
  { id: '804', name: 'Costela bovina', categoryId: '108' },
  {
    id: '808',
    name: 'Jacaré (carne bovina de segunda c/ osso)',
    categoryId: '108',
  },
  { id: '811', name: 'Filé de segunda', categoryId: '108' },
  { id: '816', name: 'Víscera bovina', categoryId: '108' },
  {
    id: '818',
    name: 'Panelada (vísceras bovinas não especificadas)',
    categoryId: '108',
  },
  { id: '820', name: 'Coração bovino', categoryId: '108' },
  { id: '824', name: 'Rim de boi', categoryId: '108' },
  { id: '825', name: 'Bofe bovino', categoryId: '108' },
  { id: '828', name: 'Miolo de boi', categoryId: '108' },
  { id: '829', name: 'Tripa bovina', categoryId: '108' },
  { id: '833', name: 'Dobradinha fresca', categoryId: '108' },
  { id: '838', name: 'Fato bovino', categoryId: '108' },
  { id: '840', name: 'Fato caprino', categoryId: '108' },
  { id: '841', name: 'Fígado bovino', categoryId: '108' },
  { id: '851', name: 'Cupim', categoryId: '108' },
  { id: '854', name: 'Língua bovina', categoryId: '108' },
  { id: '860', name: 'Rabada de boi', categoryId: '108' },
  { id: '861', name: 'Mocotó bovino', categoryId: '108' },
  { id: '865', name: 'Braço bovino', categoryId: '108' },
  { id: '866', name: 'Mão bovina', categoryId: '108' },
  { id: '867', name: 'Carré', categoryId: '108' },
  { id: '871', name: 'Bisteca suína', categoryId: '108' },
  { id: '878', name: 'Pernil suíno', categoryId: '108' },
  { id: '882', name: 'Quarto suíno', categoryId: '108' },
  { id: '883', name: 'Costela suína', categoryId: '108' },
  { id: '892', name: 'Lombo suíno', categoryId: '108' },
  { id: '896', name: 'Toucinho', categoryId: '108' },
  { id: '897', name: 'Míudo suíno', categoryId: '108' },
  { id: '898', name: 'Arrasto suíno', categoryId: '108' },
  { id: '899', name: 'Sarapatel suíno fresco', categoryId: '108' },
  { id: '90', name: 'Macaxeira', categoryId: '101' },
  { id: '900', name: 'Carne suína', categoryId: '108' },
  { id: '911', name: 'Carne moída', categoryId: '108' },
  { id: '912', name: 'Carne moída', categoryId: '108' },
  { id: '923', name: 'Guisado', categoryId: '108' },
  { id: '924', name: 'Tripa suína', categoryId: '108' },
  { id: '926', name: 'Figado suíno', categoryId: '108' },
  { id: '929', name: 'Língua suína', categoryId: '108' },
  { id: '934', name: 'Orelha suína fresca', categoryId: '108' },
  { id: '935', name: 'Sarrabulho', categoryId: '108' },
  { id: '936', name: 'Mocotó suíno', categoryId: '108' },
  { id: '937', name: 'Carne de cabrito', categoryId: '108' },
  { id: '94', name: 'Cará', categoryId: '101' },
  { id: '940', name: 'Carne de bode', categoryId: '108' },
  { id: '941', name: 'Carne de bode', categoryId: '108' },
  { id: '944', name: 'Carne caprina', categoryId: '108' },
  { id: '948', name: 'Carne de caprino', categoryId: '108' },
  { id: '951', name: 'Carne de carneiro', categoryId: '108' },
  { id: '956', name: 'Carne de ovelha', categoryId: '108' },
  { id: '960', name: 'Mocotó de caprino', categoryId: '108' },
  { id: '961', name: 'Pernil', categoryId: '108' },
  { id: '965', name: 'Lagarto bovino', categoryId: '108' },
  { id: '970', name: 'Alcatra suína', categoryId: '108' },
  { id: '972', name: 'Alcatra suína', categoryId: '108' },
  { id: '973', name: 'Brachola', categoryId: '108' },
  { id: '974', name: 'Bife role cru', categoryId: '108' },
  { id: '975', name: 'Buchada de bode', categoryId: '108' },
  { id: '976', name: 'Suã suína', categoryId: '108' },
  { id: '978', name: 'Carne de outros animais', categoryId: '108' },
  { id: '987', name: 'Carne da paca', categoryId: '108' },
  { id: '990', name: 'Carne de jacaré', categoryId: '108' },
  { id: '992', name: 'Carne de capivara', categoryId: '108' },
  { id: '995', name: 'Carne de cotia', categoryId: '108' },
  { id: '997', name: 'Carne de jabuti', categoryId: '108' },
  { id: '998', name: 'Carne de primeira', categoryId: '108' },
];

const preparation = [
  { id: '1', name: 'Cru(a)' },
  { id: '10', name: 'Ao alho e óleo' },
  { id: '11', name: 'Com manteiga/óleo' },
  { id: '12', name: 'Ao vinagrete' },
  { id: '13', name: 'Ensopado' },
  { id: '14', name: 'Mingau' },
  { id: '15', name: 'Sopa' },
  { id: '2', name: 'Cozido(a)' },
  { id: '3', name: 'Grelhado(a)/brasa/churrasco' },
  { id: '4', name: 'Assado(a)' },
  { id: '5', name: 'Frito(a)' },
  { id: '6', name: 'Empanado(a)/à milanesa' },
  { id: '7', name: 'Refogado(a)' },
  { id: '8', name: 'Molho vermelho' },
  { id: '9', name: 'Molho branco' },
  { id: '99', name: 'Não se aplica' },
];

async function main() {
  await prisma.category.createMany({
    data: category,
  });

  await prisma.preparation.createMany({
    data: preparation,
  });

  await prisma.food.createMany({
    data: food,
  });

  await prisma.nutritional_data.createMany({
    data: nutritionalData.map((item, index) => {
      const object: NutritionalData = {
        id: (index + 1).toFixed(),
        foodId: item.foodId,
        categoryId: item.categoryId,
        preparationId: item.preparationId,
      };
      Object.keys(item).forEach((key) => {
        if (item[key as keyof typeof item]) {
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore
          object[key] = item[key as keyof typeof item];
        }
      });
      return object as NutritionalData;
    }),
  });
}
main()
  .then(() => {
    console.log('Seeds executadas com sucesso!');
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
